
from PyQt5 import QtCore, QtGui, QtWidgets
from datetime import datetime
from playsound import playsound
from ayarlar1 import Ui_Form_ayar
from listeleme import Ui_Form_listele
from stokekle import Ui_Form_stokekle
from tanımlama import Ui_Form_tanimlama
import sqlite3
baglanti = sqlite3.connect(".\Data\stok.db")
islem = baglanti.cursor()
class Ui_Form_ana(object):
    def setupUi_ana(self, Form):
        Form.setObjectName("Form")
        Form.resize(1222, 789)
        Form.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        Form.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/self/Stok/warehouse (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(100, 60, 1021, 671))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.widget.setFont(font)
        self.widget.setStyleSheet("\n"
"\n"
"QPushButton{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(11, 131, 120, 219), stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba(255, 255, 255, 210);\n"
"    border-radius:5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(150, 123, 111, 219), stop:1 rgba(85, 81, 84, 226));\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(150, 123, 111, 255);\n"
"}\n"
"\n"
"\n"
"")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(-10, 0, 1031, 51))
        self.label.setStyleSheet("background-color: rgb(216, 186, 179);\n"
"border-rauis : 50px")
        self.label.setText("")
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(0, 0, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/self/Stok/warehouse.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.stokekle)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setGeometry(QtCore.QRect(276, 0, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/self/Stok/in-stock.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon2)
        self.pushButton_2.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.stoklistele)
        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        self.pushButton_3.setGeometry(QtCore.QRect(558, 0, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/self/Stok/inventory.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon3)
        self.pushButton_3.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.clicked.connect(self.tanimla)
        self.pushButton_4 = QtWidgets.QPushButton(self.widget)
        self.pushButton_4.setGeometry(QtCore.QRect(840, 0, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/self/Stok/man.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon4)
        self.pushButton_4.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(0, 50, 1021, 851))
        self.label_2.setStyleSheet("background-color: rgb(121, 121, 121);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.pushButton_6 = QtWidgets.QPushButton(self.widget)
        self.pushButton_6.setGeometry(QtCore.QRect(890, 620, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("border-left-radius: 25px;")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/self/Stok/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon5)
        self.pushButton_6.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_6.clicked.connect(self.cikis)
        self.frame_2 = QtWidgets.QFrame(self.widget)
        self.frame_2.setGeometry(QtCore.QRect(820, 140, 191, 211))
        font = QtGui.QFont()
        font.setFamily("ui-sans-serif,system-ui,-apple-system,system-ui,Segoe UI,Roboto,Helvetica Neue,Arial,Noto Sans,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji")
        font.setPointSize(9)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.frame_2.setFont(font)
        self.frame_2.setStyleSheet(" background-color: #3DD1E7;\n"
"  border: 0 solid #E5E7EB;\n"
"border-radius: 28px;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(40, 0, 121, 111))
        self.label_3.setStyleSheet("border-image: url(:/self/Stok/man (1).png);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(40, 130, 141, 61))
        font = QtGui.QFont()
        font.setFamily("ui-sans-serif,system-ui,-apple-system,system-ui,Segoe UI,Roboto,Helvetica Neue,Arial,Noto Sans,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji")
        font.setPointSize(17)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_6.setFont(font)
        self.label_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_6.setTextFormat(QtCore.Qt.AutoText)
        self.label_6.setObjectName("label_6")
        self.frame_5 = QtWidgets.QFrame(self.widget)
        self.frame_5.setGeometry(QtCore.QRect(20, 70, 501, 281))
        font = QtGui.QFont()
        font.setFamily("ui-sans-serif,system-ui,-apple-system,system-ui,Segoe UI,Roboto,Helvetica Neue,Arial,Noto Sans,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji")
        font.setPointSize(9)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.frame_5.setFont(font)
        self.frame_5.setStyleSheet(" background-color: #3DD1E7;\n"
"border-radius: 28px;\n"
"\n"
"")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_5 = QtWidgets.QLabel(self.frame_5)
        self.label_5.setGeometry(QtCore.QRect(30, 20, 211, 221))
        self.label_5.setStyleSheet("border-image: url(:/self/Stok/stock.png);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(self.frame_5)
        self.label_7.setGeometry(QtCore.QRect(260, 40, 241, 71))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(103, 103, 103);")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame_5)
        self.label_8.setGeometry(QtCore.QRect(290, 110, 231, 111))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.frame_8 = QtWidgets.QFrame(self.widget)
        self.frame_8.setGeometry(QtCore.QRect(814, 64, 201, 51))
        font = QtGui.QFont()
        font.setFamily("ui-sans-serif,system-ui,-apple-system,system-ui,Segoe UI,Roboto,Helvetica Neue,Arial,Noto Sans,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji")
        font.setPointSize(9)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.frame_8.setFont(font)
        self.frame_8.setStyleSheet("background-color: #3DD1E7;\n"
"\n"
"\n"
"\n"
"")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.label_4 = QtWidgets.QLabel(self.frame_8)
        self.label_4.setGeometry(QtCore.QRect(33, 10, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.frame_9 = QtWidgets.QFrame(self.frame_8)
        self.frame_9.setGeometry(QtCore.QRect(0, 0, 201, 51))
        font = QtGui.QFont()
        font.setFamily("ui-sans-serif,system-ui,-apple-system,system-ui,Segoe UI,Roboto,Helvetica Neue,Arial,Noto Sans,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji")
        font.setPointSize(9)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.frame_9.setFont(font)
        self.frame_9.setStyleSheet("background-color: #3DD1E7;\n"
"\n"
"\n"
"\n"
"")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.label_13 = QtWidgets.QLabel(self.frame_9)
        self.label_13.setGeometry(QtCore.QRect(33, 10, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.frame_10 = QtWidgets.QFrame(self.frame_9)
        self.frame_10.setGeometry(QtCore.QRect(0, 0, 201, 51))
        font = QtGui.QFont()
        font.setFamily("ui-sans-serif,system-ui,-apple-system,system-ui,Segoe UI,Roboto,Helvetica Neue,Arial,Noto Sans,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji")
        font.setPointSize(9)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.frame_10.setFont(font)
        self.frame_10.setStyleSheet("background-color: #3DD1E7;\n"
"\n"
"\n"
"\n"
"")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.label_14 = QtWidgets.QLabel(self.frame_10)
        self.label_14.setGeometry(QtCore.QRect(33, 10, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.tarih = datetime.now()
        self.frame_6 = QtWidgets.QFrame(self.widget)
        self.frame_6.setGeometry(QtCore.QRect(20, 370, 501, 281))
        font = QtGui.QFont()
        font.setFamily("ui-sans-serif,system-ui,-apple-system,system-ui,Segoe UI,Roboto,Helvetica Neue,Arial,Noto Sans,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji")
        font.setPointSize(9)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.frame_6.setFont(font)
        self.frame_6.setStyleSheet(" background-color: #3DD1E7;\n"
"border-radius: 28px;\n"
"\n"
"")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_9 = QtWidgets.QLabel(self.frame_6)
        self.label_9.setGeometry(QtCore.QRect(30, 20, 231, 221))
        self.label_9.setStyleSheet("border-image: url(:/self/Stok/wheelbarrow.png);")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.frame_6)
        self.label_10.setGeometry(QtCore.QRect(250, 50, 251, 71))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: rgb(103, 103, 103);")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.frame_6)
        self.label_11.setGeometry(QtCore.QRect(290, 120, 231, 111))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.widget)
        self.label_12.setGeometry(QtCore.QRect(820, 360, 191, 171))
        self.label_12.setStyleSheet("border-image: url(:/self/Stok/welcome.png);")
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.pushButton_7 = QtWidgets.QPushButton(self.widget)
        self.pushButton_7.setGeometry(QtCore.QRect(890, 560, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("border-left-radius: 25px;")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/newPrefix/Stok/work-process.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_7.setIcon(icon6)
        self.pushButton_7.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_7.clicked.connect(self.ayarlar)
        self.frame_7 = QtWidgets.QFrame(self.widget)
        self.frame_7.setGeometry(QtCore.QRect(530, 70, 271, 281))
        font = QtGui.QFont()
        font.setFamily("ui-sans-serif,system-ui,-apple-system,system-ui,Segoe UI,Roboto,Helvetica Neue,Arial,Noto Sans,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji")
        font.setPointSize(9)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.frame_7.setFont(font)
        self.frame_7.setStyleSheet(" background-color: #3DD1E7;\n"
"border-radius: 28px;\n"
"\n"
"")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.label_15 = QtWidgets.QLabel(self.frame_7)
        self.label_15.setGeometry(QtCore.QRect(50, 0, 181, 81))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("color: rgb(103, 103, 103);")
        self.label_15.setObjectName("label_15")
        self.frame_11 = QtWidgets.QFrame(self.frame_7)
        self.frame_11.setGeometry(QtCore.QRect(0, 0, 271, 281))
        font = QtGui.QFont()
        font.setFamily("ui-sans-serif,system-ui,-apple-system,system-ui,Segoe UI,Roboto,Helvetica Neue,Arial,Noto Sans,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji")
        font.setPointSize(9)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.frame_11.setFont(font)
        self.frame_11.setStyleSheet(" background-color: #3DD1E7;\n"
"border-radius: 28px;\n"
"\n"
"")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.label_16 = QtWidgets.QLabel(self.frame_11)
        self.label_16.setGeometry(QtCore.QRect(50, 0, 181, 81))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("color: rgb(103, 103, 103);")
        self.label_16.setObjectName("label_16")
        self.label_18 = QtWidgets.QLabel(self.frame_11)
        self.label_18.setGeometry(QtCore.QRect(10, 90, 181, 81))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("color: rgb(103, 103, 103);")
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.frame_11)
        self.label_19.setGeometry(QtCore.QRect(23, 159, 181, 81))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("color: rgb(103, 103, 103);")
        self.label_19.setObjectName("label_19")
        self.label_22 = QtWidgets.QLabel(self.frame_11)
        self.label_22.setGeometry(QtCore.QRect(197, 123, 55, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.frame_11)
        self.label_23.setGeometry(QtCore.QRect(197, 192, 55, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_23.setObjectName("label_23")
        self.label_26 = QtWidgets.QLabel(self.frame_11)
        self.label_26.setGeometry(QtCore.QRect(90, 60, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_26.setObjectName("label_26")
        self.frame_12 = QtWidgets.QFrame(self.widget)
        self.frame_12.setGeometry(QtCore.QRect(530, 370, 271, 281))
        font = QtGui.QFont()
        font.setFamily("ui-sans-serif,system-ui,-apple-system,system-ui,Segoe UI,Roboto,Helvetica Neue,Arial,Noto Sans,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji")
        font.setPointSize(9)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.frame_12.setFont(font)
        self.frame_12.setStyleSheet(" background-color: #3DD1E7;\n"
"border-radius: 28px;\n"
"\n"
"")
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.label_17 = QtWidgets.QLabel(self.frame_12)
        self.label_17.setGeometry(QtCore.QRect(60, 0, 181, 81))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("color: rgb(103, 103, 103);")
        self.label_17.setObjectName("label_17")
        self.label_20 = QtWidgets.QLabel(self.frame_12)
        self.label_20.setGeometry(QtCore.QRect(21, 149, 181, 81))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("color: rgb(103, 103, 103);")
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.frame_12)
        self.label_21.setGeometry(QtCore.QRect(10, 80, 181, 81))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("color: rgb(103, 103, 103);")
        self.label_21.setObjectName("label_21")
        self.label_24 = QtWidgets.QLabel(self.frame_12)
        self.label_24.setGeometry(QtCore.QRect(180, 112, 55, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.frame_12)
        self.label_25.setGeometry(QtCore.QRect(180, 180, 55, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_25.setObjectName("label_25")
        self.label_27 = QtWidgets.QLabel(self.frame_12)
        self.label_27.setGeometry(QtCore.QRect(90, 60, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_27.setObjectName("label_27")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Stok Programı "))
        self.pushButton.setText(_translate("Form", "Stok Ekle"))
        self.pushButton_2.setText(_translate("Form", "Ürünler"))
        self.pushButton_3.setText(_translate("Form", "Tanımlamalar"))
        self.pushButton_4.setText(_translate("Form", "Kullanıcı Ekle"))
        self.pushButton_6.setText(_translate("Form", "Çıkış"))
        islem.execute("select giris from giris")
        self.giris = islem.fetchall()
        for a in self.giris:
                self.label_6.setText(_translate("Form", "  {}".format(a[0])))
        self.label_7.setText(_translate("Form", "Toplam Stok Miktarı"))
        islem.execute("select tarih from ana")
        self.toplamstok = islem.fetchall()
        toplam = []
        for a in self.toplamstok:
                toplam.append(a[0])
        self.label_8.setText(_translate("Form", "{}".format(len(toplam))))
        self.label_4.setText(_translate("Form", "12.01.2023"))
        self.label_13.setText(_translate("Form", "12.01.2023"))
        self.label_14.setText(_translate("Form", "{}".format(self.tarih.date())))
        self.label_10.setText(_translate("Form", "Bügün Eklenen Stok"))
        self.bugun = []
        for i in self.toplamstok:
                if i[0] == str(self.tarih.date()):
                        self.bugun.append(i[0])
        self.label_11.setText(_translate("Form", "{}".format(len(self.bugun))))
        self.pushButton_7.setText(_translate("Form", "AYARLAR"))
        self.label_15.setText(_translate("Form", "MAİL SİSTEMİ"))
        self.label_16.setText(_translate("Form", "MAİL SİSTEMİ"))
        self.label_18.setText(_translate("Form", "KULLANICI MAİL AT   :"))
        self.label_19.setText(_translate("Form", "STOK MAİL AT          :"))
        islem.execute("select kullanıcı from mail")
        kullanici = islem.fetchall()
        for i in kullanici:
                if i[0] == "kapalı":
                        self.label_22.setText(_translate("Form", "KAPALI"))
                if i[0] == "açık":
                        self.label_22.setText(_translate("Form", "AÇIK"))
        islem.execute("select stok from mail")
        stok = islem.fetchall()
        for i in stok:
                if i[0] == "kapalı":
                        self.label_23.setText(_translate("Form", "KAPALI"))
                if i[0] == "açık":
                        self.label_23.setText(_translate("Form", "AÇIK"))
        islem.execute("select konum from mail")
        mail = islem.fetchall()
        for i in mail:
                if i[0] == "kapalı":
                        self.label_26.setText(_translate("Form", "KAPALI"))
                if i[0] == "açık":
                        self.label_26.setText(_translate("Form", "AÇIK"))
        self.label_17.setText(_translate("Form", "SES SİSTEMİ"))
        self.label_20.setText(_translate("Form", "STOK SES            :"))
        self.label_21.setText(_translate("Form", "GİRİŞ SES              :"))
        islem.execute("select kullanıcı from ses")
        seskullanici = islem.fetchall()
        for i in seskullanici:
                if i[0] == "kapalı":
                        self.label_24.setText(_translate("Form", "KAPALI"))
                if i[0] == "açık":
                        self.label_24.setText(_translate("Form", "AÇIK"))
        islem.execute("select stok from ses")
        stokses = islem.fetchall()
        for i in stokses:
                if i[0] == "kapalı":
                        self.label_25.setText(_translate("Form", "KAPALI"))
                if i[0] == "açık":
                        self.label_25.setText(_translate("Form", "AÇIK"))
        islem.execute("select konum from ses")
        sesci = islem.fetchall()
        for i in sesci:
                if i[0] == "kapalı":
                        self.label_27.setText(_translate("Form", "KAPALI"))
                if i[0] == "açık":
                        self.label_27.setText(_translate("Form", "AÇIK"))
        islem.execute("select konum from ses")
        kullanici = islem.fetchall()
        for i in kullanici:
                if i[0] == "açık":
                        islem.execute("select kullanıcı from ses")
                        kullan = islem.fetchall()
                        for i in kullan:
                                if i[0] == "açık":
                                        try:
                                               playsound("Başlangı.mp3")

                                        except:
                                                pass
    def cikis(self):
        sys.exit()
    def ayarlar(self):
        self.ayar_pencere = QtWidgets.QMainWindow()
        self.ui1 = Ui_Form_ayar()
        self.ui1.setupUi(self.ayar_pencere)
        self.ayar_pencere.show()
    def stokekle(self):
        self.stok_pencere = QtWidgets.QMainWindow()
        self.ui2 = Ui_Form_stokekle()
        self.ui2.setupUi(self.stok_pencere)
        self.stok_pencere.show()
    def stoklistele(self):
        self.liste_pencere = QtWidgets.QMainWindow()
        self.ui3 = Ui_Form_listele()
        self.ui3.setupUi(self.liste_pencere)
        self.liste_pencere.show()
    def tanimla(self):
        self.tanimlama_pencere = QtWidgets.QMainWindow()
        self.ui4 = Ui_Form_tanimlama()
        self.ui4.setupUi(self.tanimlama_pencere)
        self.tanimlama_pencere.show()

import resim1_rc
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ana_pencere = QtWidgets.QMainWindow()
    ui = Ui_Form_ana()
    ui.setupUi_ana(ana_pencere)
    ana_pencere.show()
    app.exec_()


